# fly.toml app configuration file generated for hire-intelligence-api on 2026-03-27T23:23:37+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hire-intelligence-api'
primary_region = 'nrt'

[build]
  dockerfile = 'Dockerfile'

[env]
  APP_ENV = 'production'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 250
    soft_limit = 200

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/health'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
